// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Ml4AoakKKuwmbGyJ7pPFvuG-TCsKoGI',
    appId: '1:32046134053:web:f8e0b6cdfa638a32f4e0cc',
    messagingSenderId: '32046134053',
    projectId: 'ludo-app-569c2',
    authDomain: 'ludo-app-569c2.firebaseapp.com',
    storageBucket: 'ludo-app-569c2.firebasestorage.app',
    measurementId: 'G-XLFHJYXFRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGzQ1Miud8kofEfKYQV2_zZG8b3pfp0Jo',
    appId: '1:32046134053:android:ec9f4719ecd2b624f4e0cc',
    messagingSenderId: '32046134053',
    projectId: 'ludo-app-569c2',
    storageBucket: 'ludo-app-569c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ2KQNQ2f0u3wUWJyglB_p5_eqd5PSa4A',
    appId: '1:32046134053:ios:25b9c42b20212479f4e0cc',
    messagingSenderId: '32046134053',
    projectId: 'ludo-app-569c2',
    storageBucket: 'ludo-app-569c2.firebasestorage.app',
    iosClientId: '32046134053-sn9kj8vcqcn01vpns63bjl996j3dhitu.apps.googleusercontent.com',
    iosBundleId: 'com.davidkasza.ludogame.ludoGame',
  );
}
